### ISSUE TITLE
"k3sup app install" is now "arkade install"   

### ISSUE THREAD

**Issue by alexellis** [rscircus/rscircus.github.io#3]
FYI, you may want to rename some of your commands where 
you use `k3sup app install`, which has now become `arkade install`

More at: https://get-arkade.dev/

Thanks, Alex

**Comment by rscircus** [comment]
Thanks, @alexellis. I'll update the article at the weekend.

**Comment by rscircus** [comment]
Added a note via https://github.com/rscircus/rscircus.github.io/commit/c4dbff7bc8a30c12a51d2bc1207de89936c80c29. As I added a bunch of `STDOUT` to my article it ain't valid anymore. I'll reference it in the next iteration trying to finally get the beloved `kubernetes-dashboard`.
